### ISSUE TITLE
Pas de test d'entrée

### ISSUE THREAD

**Issue by gekkoxiii** [projet-progam-imperative/tictactoe_3#1]
Si on tape une lettre au lieu d'un entier de 0 à 8, ca part en boucle......

**Comment by gekkoxiii** [comment]
Proposition
        printf("entrer le num de la case (0 -> 8)");
        c=getchar();
        if ((int)c>47 && (int)c<57){
                i=atoi(&c);
        }else{i=9;}
        if(i<9){
        //printf("i vaut :%i\n c vaut : %i\n",i,c);
        plateau = turn(plateau,i);
        }
        while (getchar() != '\n');

**Comment by bobbywan-kenoby** [comment]
problem solved
